// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {ai} from '../models';
import {desktop} from '../models';
import {wa} from '../models';
import {http} from '../models';

export function AIChat(arg1:string,arg2:Array<main.PlaygroundMessage>,arg3:main.PlaygroundOptions):Promise<void>;

export function AIChatCancel():Promise<void>;

export function AICompose(arg1:string,arg2:string):Promise<string>;

export function AIListModels(arg1:ai.Config):Promise<Array<string>>;

export function AISuggestReplies(arg1:string,arg2:string):Promise<Array<string>>;

export function AISummarize(arg1:string):Promise<string>;

export function AITestConnection(arg1:ai.Config):Promise<void>;

export function ArchiveChat(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function BlockChat(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteMessage(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function DesktopCloseApp(arg1:string):Promise<void>;

export function DesktopGetVolume():Promise<number>;

export function DesktopListApps():Promise<Array<desktop.AppInfo>>;

export function DesktopLockScreen():Promise<void>;

export function DesktopMediaNext():Promise<void>;

export function DesktopMediaNowPlaying():Promise<desktop.MediaInfo>;

export function DesktopMediaPlayPause():Promise<void>;

export function DesktopMediaPrev():Promise<void>;

export function DesktopOpenApp(arg1:string):Promise<void>;

export function DesktopScreenshot():Promise<string>;

export function DesktopSetVolume(arg1:number):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ForwardMessage(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function GetAIConfig():Promise<ai.Config>;

export function GetGroupInfo(arg1:string,arg2:string):Promise<wa.GroupInfo>;

export function IsOnWhatsApp(arg1:string,arg2:Array<string>):Promise<Array<wa.ContactCheck>>;

export function LeaveGroup(arg1:string,arg2:string):Promise<void>;

export function ListSessions():Promise<Array<wa.SessionInfo>>;

export function ListStarred(arg1:string,arg2:number):Promise<Array<wa.MessageInfo>>;

export function LoadChats(arg1:string):Promise<Array<wa.ChatInfo>>;

export function LoadMessages(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<wa.MessageInfo>>;

export function Logout(arg1:string):Promise<void>;

export function MarkRead(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function MediaHTTPHandler():Promise<http.Handler>;

export function MuteChat(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function PickFile(arg1:string):Promise<string>;

export function PinChat(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function PostStatusImage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function PostStatusText(arg1:string,arg2:string):Promise<string>;

export function Quit():Promise<void>;

export function ReactMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function RefreshAvatar(arg1:string,arg2:string):Promise<void>;

export function SaveTempBlob(arg1:string,arg2:string):Promise<string>;

export function SearchMessages(arg1:string,arg2:string,arg3:number):Promise<Array<wa.MessageInfo>>;

export function SendAudio(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:main.QuotedArg):Promise<wa.SendMediaResult>;

export function SendChatPresence(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendDocument(arg1:string,arg2:string,arg3:string,arg4:main.QuotedArg):Promise<wa.SendMediaResult>;

export function SendImage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:main.QuotedArg):Promise<wa.SendMediaResult>;

export function SendText(arg1:string,arg2:string,arg3:string,arg4:main.QuotedArg):Promise<string>;

export function SendVideo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:main.QuotedArg):Promise<wa.SendMediaResult>;

export function SetAIConfig(arg1:ai.Config):Promise<void>;

export function SetGroupName(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetSelfProfilePicture(arg1:string,arg2:string):Promise<void>;

export function SetSelfStatus(arg1:string,arg2:string):Promise<void>;

export function StarMessage(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function StartLogin(arg1:string):Promise<string>;

export function SubscribePresence(arg1:string,arg2:string):Promise<void>;

export function UpdateGroupParticipants(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;

export function WindowHide():Promise<void>;

export function WindowMinimize():Promise<void>;

export function WindowShow():Promise<void>;

export function WindowToggleMaximize():Promise<void>;
